config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
    collection do
      post :confirm
    end
    member do
      patch :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true, length: { in: 1..140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create    
    @blog = Blog.create(params.require(:blog).permit(:title, :content))
    if @blog.save
      redirect_to new_blog_path, notice:"登録しました"
    elsif
      render :new
    end
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    @blog.update(params.require(:blog).permit(:title, :content))
    if @blog.save
      redirect_to blogs_path, notice:"修正しました"
    elsif
      render :edit
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path, notice:"削除しました"
  end

  def confirm
    @blog = Blog.new(params.require(:blog).permit(:title, :content))
    @blog.id = params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def new_or_edit
    if action_name == 'new'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/views/blogs/confirm.html.erb
<p>以下で登録しますか？</p>
<%= form_with(model: @blog, local: true)do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <%= form.submit "登録する" %>
<% end %>

app/views/blogs/edit.html.erb
<%= form_with(model: @blog, local: true, url: new_or_edit) do |form| %>
    <% if @blog.errors.any? %>
      <div id="error_explanation">
      <h2>エラーが<%= @blog.errors.count %>件あります。</h2>
        <ul>
          <% @blog.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="blog_title">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
    <div class="blog_content">
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>
    <%= form.submit "Registration" %>
  <% end %>
  <%= link_to 'ブログ一覧へ', blogs_path %>

app/views/blogs/index.html.erb
<h1>ブログ一覧</h1>
<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
  </tr>
<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
    <td><%= link_to '編集', edit_blog_path(blog.id) %></td>
    <td><%= link_to '削除', blog_path(blog.id), method: :delete %></td>
  </tr>
<% end %>
</table>
<%= link_to 'ブログ作成画面へ', new_blog_path %>

app/views/blogs/new.html.erb
<h1>Create Blog Content</h1>

<%= form_with(model: @blog, local: true, url: confirm_blogs_path) do |form| %>

  <% if @blog.errors.any? %> 
    <div class="error_explanation">
    <h2>エラーが<%= @blog.errors.count %>件あります。</h2>
      <ul>
        <% @blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="blog_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <%= form.submit %>

<% end %>
<%= link_to 'ブログ一覧へ',blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsExec2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>